# Generated by Django 5.2.3 on 2025-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_city_profile_first_name_profile_house_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='Unknown', max_length=15),
        ),
    ]
