# Generated by Django 5.2.3 on 2025-09-12 13:14

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0010_product_is_listed'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=32)),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('postcode', models.CharField(blank=True, max_length=20, null=True)),
                ('town_or_city', models.CharField(max_length=40)),
                ('street_address1', models.CharField(max_length=80)),
                ('street_address2', models.CharField(blank=True, max_length=80, null=True)),
                ('county', models.CharField(blank=True, max_length=80, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, help_text='Optional fuel/delivery fee (e.g., for local delivery)', max_digits=6, null=True)),
                ('deposit_total', models.DecimalField(decimal_places=2, default=0, help_text='Security deposit total', max_digits=6)),
                ('site_fee', models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (10% of rental total)', max_digits=6)),
                ('order_total', models.DecimalField(decimal_places=2, default=0, help_text='Rental subtotal (excluding deposit/site fee)', max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, help_text='Final total including delivery, deposit, site fee', max_digits=10)),
                ('original_checkout', models.TextField(default='', help_text='Snapshot of the checkout session at the time of order')),
                ('stripe_pid', models.CharField(default='', max_length=254)),
                ('order_status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_use', 'In Use'), ('returned', 'Returned'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('rental_duration', models.PositiveIntegerField(default=1, help_text='Duration in days')),
                ('lineitem_total', models.DecimalField(decimal_places=2, editable=False, max_digits=9)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineitems', to='checkout.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.product')),
            ],
        ),
    ]
