# Generated by Django 5.2.3 on 2025-09-03 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='site_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Platform fee (10% of rental total)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final total including delivery, deposit, site fee', max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Rental subtotal (excluding deposit/site fee)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderlineitem',
            name='lineitem_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=9),
        ),
    ]
