# Generated by Django 5.2.3 on 2025-07-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_remove_product_image_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=254, unique=True),
        ),
    ]
