# Generated by Django 5.2.3 on 2025-09-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_delete_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_listed',
            field=models.BooleanField(db_index=True, default=True, help_text='Unlist to hide the item from renters.'),
        ),
    ]
